<?php

/**
 * @file
 * Module file for icucommittees_module.
 */

// Registered URLs for this club
function icucommittees_menu() {

  $items['committees'] = array(
      'page callback' => 'icucommittees', // Page function
      'page arguments' => array(), // No parameter (starting at 0)
      'type' => MENU_CALLBACK, // Do not show menu item
      'access callback' => TRUE, // Page always accessible
  );
                    
  $items['committees/%'] = array(
    'page callback' => 'icucommittees_year', // Page function
    'page arguments' => array(1), // The year is the 2nd parameter (starting at 0)
    'type' => MENU_CALLBACK, // Do not show menu item
    'access callback' => TRUE, // Page always accessible
  );

  $items['committees/%/%'] = array(
    'page callback' => 'icucommittees_year_board', // Page function
    'page arguments' => array(1,2), // The year is the 2nd parameter and board is 3rd (starting at 0)
    'type' => MENU_CALLBACK, // Do not show menu item
    'access callback' => TRUE, // Page always accessible
  );

  $items['committees/%/%/%'] = array(
      'page callback' => 'icucommittees_year_board_meeting', // Page function
      'page arguments' => array(1,2,3), // The centre is the 2nd parameter (starting at 0)
      'type' => MENU_CALLBACK, // Do not show menu item
      'access callback' => TRUE, // Page always accessible
   );

$items['committees/%/%/%/%'] = array(
    'page callback' => 'icucommittees_file', // Page function
    'page arguments' => array(4), // The file is the 5th parameter (starting at 0)
    'type' => MENU_CALLBACK, // Do not show menu item
    'access callback' => TRUE, // Page always accessible
  );

  return $items;
}

// Define templates
function icucommittees_theme() {
    return array(
    
     'icucommittees' => array( // name of theme
                 'template' => 'icucommittees' // name of template to load, .tpl.php will be added
                         ),
                         
     'icucommittees_year' => array( // name of theme
            'template' => 'icucommittees_year' // name of template to load, .tpl.php will be added
        ),
        
     'icucommittees_year_board' => array( // name of theme
         'template' => 'icucommittees_year_board' // name of template to load, .tpl.php will be added
        ),

     'icucommittees_year_board_meeting' => array( // name of theme
                 'template' => 'icucommittees_year_board_meeting' // name of template to load, .tpl.php will be added
                          ),
    );
}

/* Non-scaffold code is below */

// callback for page
function icucommittees_file($fileID) {

  $db = @mssql_connect(variable_get('icuerpol_hostname'), variable_get('icuerpol_username'), variable_get('icuerpol_password'));
  if(!$db) {

    drupal_not_found(); // database down
    return;
  }

  mssql_select_db(variable_get('icuerpol_database'));

  // Avoid truncation
  mssql_query ( 'SET TEXTSIZE 2147483647', $db);
  ini_set ( 'mssql.textlimit', '2147483647');
  ini_set ( 'mssql.textsize', '2147483647');

  // Image
	$result = mssql_query("SELECT * FROM CommitteeMeetingPapers WHERE ID = '$fileID'");
	if(mssql_num_rows($result) != '1'){
	drupal_not_found(); //Stops people being able to download whole UpFiles table!
	}
	$fileID = mssql_result($result, 0, "FileID");
  $result = mssql_query("SELECT * FROM UpFiles WHERE ID = '$fileID'");
  if(mssql_num_rows($result) != '1') {
     drupal_not_found();
  }

  $res = mssql_fetch_object($result);
  if(!is_object($res)) {
     drupal_not_found();
  }
  header('Content-Type: '.$res->FileType);
  echo $res->UpFile;
  return;
}

function icucommittees(){
	$db = @mssql_connect(variable_get('icuerpol_hostname'), variable_get('icuerpol_username'), variable_get('icuerpol_password'));
	if(!$db) {
      		drupal_not_found(); // database down
        	return;
        }
    mssql_select_db(variable_get('icuerpol_database'));
	$result = mssql_query("SELECT DISTINCT Years.YearDesc, Years.YearStart FROM CommitteeMeetings INNER JOIN Years ON Years.YearID = CommitteeMeetings.YearID ORDER BY Years.YearStart, Years.YearDesc ASC");
	$numresult = mssql_num_rows($result);
	$row1 = array();
	$k=0;	
	while($row = mssql_fetch_assoc($result)){
		$row1[$k] = $row['YearDesc'];
	$k++;	
	}
	mssql_close($db);
    drupal_set_title(t('Committees'));
	$output = theme("icucommittees", array('row1' => $row1));
	return $output;
}

function icucommittees_year($year){
	$db = @mssql_connect(variable_get('icuerpol_hostname'), variable_get('icuerpol_username'), variable_get('icuerpol_password'));
	if(!$db) {
      		drupal_not_found(); // database down
        	return;
        }
    mssql_select_db(variable_get('icuerpol_database'));
	$result = mssql_query("SELECT DISTINCT Years.YearDesc, Years.YearStart FROM CommitteeMeetings INNER JOIN Years ON Years.YearID = CommitteeMeetings.YearID ORDER BY Years.YearStart, Years.YearDesc ASC");
	$numresult = mssql_num_rows($result);
	$row1 = array();
	$k=0;	
	while($row = mssql_fetch_assoc($result)){
		$row1[$k] = $row['YearDesc'];
	$k++;	
	}

$yearIDquery = mssql_query("SELECT * FROM Years WHERE YearDesc = '$year'");
$yearID = mssql_result($yearIDquery, 0, "YearID");
	
for($j=0;$j<=3;$j++){
		$case1 = mssql_query("SELECT DISTINCT CommitteeMeetings.CommitteeID FROM CommitteeMeetings INNER JOIN Committees ON CommitteeMeetings.CommitteeID = Committees.ID WHERE CommitteeMeetings.YearID = '$yearID' AND Committees.CommitteeTier = '$j'");
		$k = 0;
while ($row = mssql_fetch_array($case1)) {
			$cough = $row['CommitteeID'];
			$case2 = mssql_query("SELECT * FROM Committees WHERE ID = '$cough'");
			$result1[$j][$k] = mssql_result($case2, 0, "CommitteeName");
			$k++;
           	}
	}
	mssql_close($db);
    drupal_set_title(t('Committees '.$year));
	$output = theme("icucommittees_year", array('row1' => $row1, 'year' => $year, 'result1' => $result1));
	return $output;
}

function icucommittees_year_board($year, $board){
	$db = @mssql_connect(variable_get('icuerpol_hostname'), variable_get('icuerpol_username'), variable_get('icuerpol_password'));
	if(!$db) {
      		drupal_not_found(); // database down
        	return;
        }
    mssql_select_db(variable_get('icuerpol_database'));
	$result = mssql_query("SELECT DISTINCT Years.YearDesc, Years.YearStart FROM CommitteeMeetings INNER JOIN Years ON Years.YearID = CommitteeMeetings.YearID ORDER BY Years.YearStart, Years.YearDesc ASC");
	$numresult = mssql_num_rows($result);
	$row1 = array();
	$k=0;	
	while($row = mssql_fetch_assoc($result)){
		$row1[$k] = $row['YearDesc'];
	$k++;	
	}

$board2 = str_replace("_"," ",$board);

$yearIDquery = mssql_query("SELECT * FROM Years WHERE YearDesc = '$year'");
$yearID = mssql_result($yearIDquery, 0, "YearID");

$CommitteeIDquery = mssql_query("SELECT * FROM Committees WHERE CommitteeName = '$board2'");

$CommitteeID = mssql_result($CommitteeIDquery, 0, "ID");
	
		$case1 = mssql_query("SELECT * FROM CommitteeMeetings WHERE YearID = '$yearID' AND CommitteeID = '$CommitteeID'");
		$request = mssql_num_rows($case1);
		$k = 0;
while ($row = mssql_fetch_array($case1)) {
			$result1[$k] = $row['MeetingDate'];
			$result2[$k] = $row['MeetingRoom'];
			$result3[$k] = $row['MeetingCancelled'];
			$result4[$k] = $row['ID'];
			$k++;
           	}
	mssql_close($db);
    drupal_set_title(t(str_replace('_', ' ', $board)));

	$output = theme("icucommittees_year_board", array('row1' => $row1, 'year' => $year, 'request' => $request, 'result1' => $result1, 'result2' => $result2, 'result3' => $result3, 'result4' => $result4, 'board' => $board));
	return $output;

}





function icucommittees_year_board_meeting($year, $board, $meeting){
	$db = @mssql_connect(variable_get('icuerpol_hostname'), variable_get('icuerpol_username'), variable_get('icuerpol_password'));
	if(!$db) {
      		drupal_not_found(); // database down
        	return;
        }
    mssql_select_db(variable_get('icuerpol_database'));
	$result = mssql_query("SELECT DISTINCT Years.YearDesc, Years.YearStart FROM CommitteeMeetings INNER JOIN Years ON Years.YearID = CommitteeMeetings.YearID ORDER BY Years.YearStart, Years.YearDesc ASC");
	$numresult = mssql_num_rows($result);
	$row1 = array();
	$k=0;	
	while($row = mssql_fetch_assoc($result)){
		$row1[$k] = $row['YearDesc'];
	$k++;	
	}

$CommitteeIDquery = mssql_query("SELECT * FROM CommitteeMeetings WHERE ID = '$meeting'");
$MeetingDate = mssql_result($CommitteeIDquery, 0, "MeetingDate");
$MeetingRoom = mssql_result($CommitteeIDquery, 0, "MeetingRoom");
$MeetingCancelled = mssql_result($CommitteeIDquery, 0, "MeetingCancelled");

$case1 = mssql_query("SELECT * FROM CommitteeMeetingPapers WHERE MeetingID = '$meeting' ORDER BY SortOrder ASC");
		$request = mssql_num_rows($case1);
		$result1 = array();
$result2 = array();
$result3 = array();
$result4 = array();
if($request != 0){
$k = 0;
while ($row = mssql_fetch_array($case1)) {
			$result1[$k] = $row['ID'];
			$result2[$k] = $row['PaperTitle'];
			$result3[$k] = $row['Agenda'];
			$result4[$k] = $row['ChangedWhen'];
			$k++;
           	}
}

	mssql_close($db);
    drupal_set_title(t(str_replace('_', ' ', $board)));
	$output = theme("icucommittees_year_board_meeting", array('MeetingDate' => $MeetingDate, 'MeetingRoom' => $MeetingRoom, 'MeetingCancelled' => $MeetingCancelled, 'row1' => $row1, 'year' => $year, 'request' => $request, 'result1' => $result1, 'result2' => $result2, 'result3' => $result3, 'result4' => $result4, 'board' => $board));
	return $output;

}





/**
 * @} End of "defgroup icuclub".
 */
